/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSlotsRouteImport } from './routes/_authenticated/admin.slots'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminPatientsRouteImport } from './routes/_authenticated/admin.patients'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin.packages'
import { Route as AuthenticatedAdminMedicinesRouteImport } from './routes/_authenticated/admin.medicines'
import { Route as AuthenticatedAdminIntakeFormRouteImport } from './routes/_authenticated/admin.intake-form'
import { Route as AuthenticatedAdminQuestionsIndexRouteImport } from './routes/_authenticated/admin.questions.index'
import { Route as AuthenticatedAdminProvidersIndexRouteImport } from './routes/_authenticated/admin.providers.index'
import { Route as AuthenticatedAdminPackagesIndexRouteImport } from './routes/_authenticated/admin.packages.index'
import { Route as AuthenticatedAdminMedicinesIndexRouteImport } from './routes/_authenticated/admin.medicines.index'
import { Route as AuthenticatedAdminQuestionsNewRouteImport } from './routes/_authenticated/admin.questions.new'
import { Route as AuthenticatedAdminQuestionsQuestionIdRouteImport } from './routes/_authenticated/admin.questions.$questionId'
import { Route as AuthenticatedAdminProvidersNewRouteImport } from './routes/_authenticated/admin.providers.new'
import { Route as AuthenticatedAdminProvidersProviderIdRouteImport } from './routes/_authenticated/admin.providers.$providerId'
import { Route as AuthenticatedAdminPackagesNewRouteImport } from './routes/_authenticated/admin.packages.new'
import { Route as AuthenticatedAdminPackagesPackageIdRouteImport } from './routes/_authenticated/admin.packages.$packageId'
import { Route as AuthenticatedAdminMedicinesNewRouteImport } from './routes/_authenticated/admin.medicines.new'
import { Route as AuthenticatedAdminMedicinesMedicineIdRouteImport } from './routes/_authenticated/admin.medicines.$medicineId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSlotsRoute = AuthenticatedAdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPatientsRoute =
  AuthenticatedAdminPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMedicinesRoute =
  AuthenticatedAdminMedicinesRouteImport.update({
    id: '/medicines',
    path: '/medicines',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntakeFormRoute =
  AuthenticatedAdminIntakeFormRouteImport.update({
    id: '/intake-form',
    path: '/intake-form',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsIndexRoute =
  AuthenticatedAdminQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminQuestionsRoute,
  } as any)
const AuthenticatedAdminProvidersIndexRoute =
  AuthenticatedAdminProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProvidersRoute,
  } as any)
const AuthenticatedAdminPackagesIndexRoute =
  AuthenticatedAdminPackagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)
const AuthenticatedAdminMedicinesIndexRoute =
  AuthenticatedAdminMedicinesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminMedicinesRoute,
  } as any)
const AuthenticatedAdminQuestionsNewRoute =
  AuthenticatedAdminQuestionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminQuestionsRoute,
  } as any)
const AuthenticatedAdminQuestionsQuestionIdRoute =
  AuthenticatedAdminQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AuthenticatedAdminQuestionsRoute,
  } as any)
const AuthenticatedAdminProvidersNewRoute =
  AuthenticatedAdminProvidersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProvidersRoute,
  } as any)
const AuthenticatedAdminProvidersProviderIdRoute =
  AuthenticatedAdminProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AuthenticatedAdminProvidersRoute,
  } as any)
const AuthenticatedAdminPackagesNewRoute =
  AuthenticatedAdminPackagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)
const AuthenticatedAdminPackagesPackageIdRoute =
  AuthenticatedAdminPackagesPackageIdRouteImport.update({
    id: '/$packageId',
    path: '/$packageId',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)
const AuthenticatedAdminMedicinesNewRoute =
  AuthenticatedAdminMedicinesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminMedicinesRoute,
  } as any)
const AuthenticatedAdminMedicinesMedicineIdRoute =
  AuthenticatedAdminMedicinesMedicineIdRouteImport.update({
    id: '/$medicineId',
    path: '/$medicineId',
    getParentRoute: () => AuthenticatedAdminMedicinesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/intake-form': typeof AuthenticatedAdminIntakeFormRoute
  '/admin/medicines': typeof AuthenticatedAdminMedicinesRouteWithChildren
  '/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRouteWithChildren
  '/admin/questions': typeof AuthenticatedAdminQuestionsRouteWithChildren
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/medicines/$medicineId': typeof AuthenticatedAdminMedicinesMedicineIdRoute
  '/admin/medicines/new': typeof AuthenticatedAdminMedicinesNewRoute
  '/admin/packages/$packageId': typeof AuthenticatedAdminPackagesPackageIdRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/providers/$providerId': typeof AuthenticatedAdminProvidersProviderIdRoute
  '/admin/providers/new': typeof AuthenticatedAdminProvidersNewRoute
  '/admin/questions/$questionId': typeof AuthenticatedAdminQuestionsQuestionIdRoute
  '/admin/questions/new': typeof AuthenticatedAdminQuestionsNewRoute
  '/admin/medicines/': typeof AuthenticatedAdminMedicinesIndexRoute
  '/admin/packages/': typeof AuthenticatedAdminPackagesIndexRoute
  '/admin/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/admin/questions/': typeof AuthenticatedAdminQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/intake-form': typeof AuthenticatedAdminIntakeFormRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/medicines/$medicineId': typeof AuthenticatedAdminMedicinesMedicineIdRoute
  '/admin/medicines/new': typeof AuthenticatedAdminMedicinesNewRoute
  '/admin/packages/$packageId': typeof AuthenticatedAdminPackagesPackageIdRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/providers/$providerId': typeof AuthenticatedAdminProvidersProviderIdRoute
  '/admin/providers/new': typeof AuthenticatedAdminProvidersNewRoute
  '/admin/questions/$questionId': typeof AuthenticatedAdminQuestionsQuestionIdRoute
  '/admin/questions/new': typeof AuthenticatedAdminQuestionsNewRoute
  '/admin/medicines': typeof AuthenticatedAdminMedicinesIndexRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesIndexRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersIndexRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/intake-form': typeof AuthenticatedAdminIntakeFormRoute
  '/_authenticated/admin/medicines': typeof AuthenticatedAdminMedicinesRouteWithChildren
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/_authenticated/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRouteWithChildren
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRouteWithChildren
  '/_authenticated/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/medicines/$medicineId': typeof AuthenticatedAdminMedicinesMedicineIdRoute
  '/_authenticated/admin/medicines/new': typeof AuthenticatedAdminMedicinesNewRoute
  '/_authenticated/admin/packages/$packageId': typeof AuthenticatedAdminPackagesPackageIdRoute
  '/_authenticated/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/_authenticated/admin/providers/$providerId': typeof AuthenticatedAdminProvidersProviderIdRoute
  '/_authenticated/admin/providers/new': typeof AuthenticatedAdminProvidersNewRoute
  '/_authenticated/admin/questions/$questionId': typeof AuthenticatedAdminQuestionsQuestionIdRoute
  '/_authenticated/admin/questions/new': typeof AuthenticatedAdminQuestionsNewRoute
  '/_authenticated/admin/medicines/': typeof AuthenticatedAdminMedicinesIndexRoute
  '/_authenticated/admin/packages/': typeof AuthenticatedAdminPackagesIndexRoute
  '/_authenticated/admin/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/_authenticated/admin/questions/': typeof AuthenticatedAdminQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/admin/intake-form'
    | '/admin/medicines'
    | '/admin/packages'
    | '/admin/patients'
    | '/admin/providers'
    | '/admin/questions'
    | '/admin/slots'
    | '/admin/'
    | '/admin/medicines/$medicineId'
    | '/admin/medicines/new'
    | '/admin/packages/$packageId'
    | '/admin/packages/new'
    | '/admin/providers/$providerId'
    | '/admin/providers/new'
    | '/admin/questions/$questionId'
    | '/admin/questions/new'
    | '/admin/medicines/'
    | '/admin/packages/'
    | '/admin/providers/'
    | '/admin/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard'
    | '/admin/intake-form'
    | '/admin/patients'
    | '/admin/slots'
    | '/admin'
    | '/admin/medicines/$medicineId'
    | '/admin/medicines/new'
    | '/admin/packages/$packageId'
    | '/admin/packages/new'
    | '/admin/providers/$providerId'
    | '/admin/providers/new'
    | '/admin/questions/$questionId'
    | '/admin/questions/new'
    | '/admin/medicines'
    | '/admin/packages'
    | '/admin/providers'
    | '/admin/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/intake-form'
    | '/_authenticated/admin/medicines'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/patients'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/slots'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/medicines/$medicineId'
    | '/_authenticated/admin/medicines/new'
    | '/_authenticated/admin/packages/$packageId'
    | '/_authenticated/admin/packages/new'
    | '/_authenticated/admin/providers/$providerId'
    | '/_authenticated/admin/providers/new'
    | '/_authenticated/admin/questions/$questionId'
    | '/_authenticated/admin/questions/new'
    | '/_authenticated/admin/medicines/'
    | '/_authenticated/admin/packages/'
    | '/_authenticated/admin/providers/'
    | '/_authenticated/admin/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/slots': {
      id: '/_authenticated/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AuthenticatedAdminSlotsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/patients': {
      id: '/_authenticated/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AuthenticatedAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/medicines': {
      id: '/_authenticated/admin/medicines'
      path: '/medicines'
      fullPath: '/admin/medicines'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/intake-form': {
      id: '/_authenticated/admin/intake-form'
      path: '/intake-form'
      fullPath: '/admin/intake-form'
      preLoaderRoute: typeof AuthenticatedAdminIntakeFormRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions/': {
      id: '/_authenticated/admin/questions/'
      path: '/'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminQuestionsRoute
    }
    '/_authenticated/admin/providers/': {
      id: '/_authenticated/admin/providers/'
      path: '/'
      fullPath: '/admin/providers/'
      preLoaderRoute: typeof AuthenticatedAdminProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProvidersRoute
    }
    '/_authenticated/admin/packages/': {
      id: '/_authenticated/admin/packages/'
      path: '/'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AuthenticatedAdminPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
    '/_authenticated/admin/medicines/': {
      id: '/_authenticated/admin/medicines/'
      path: '/'
      fullPath: '/admin/medicines/'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminMedicinesRoute
    }
    '/_authenticated/admin/questions/new': {
      id: '/_authenticated/admin/questions/new'
      path: '/new'
      fullPath: '/admin/questions/new'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsNewRouteImport
      parentRoute: typeof AuthenticatedAdminQuestionsRoute
    }
    '/_authenticated/admin/questions/$questionId': {
      id: '/_authenticated/admin/questions/$questionId'
      path: '/$questionId'
      fullPath: '/admin/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuestionsRoute
    }
    '/_authenticated/admin/providers/new': {
      id: '/_authenticated/admin/providers/new'
      path: '/new'
      fullPath: '/admin/providers/new'
      preLoaderRoute: typeof AuthenticatedAdminProvidersNewRouteImport
      parentRoute: typeof AuthenticatedAdminProvidersRoute
    }
    '/_authenticated/admin/providers/$providerId': {
      id: '/_authenticated/admin/providers/$providerId'
      path: '/$providerId'
      fullPath: '/admin/providers/$providerId'
      preLoaderRoute: typeof AuthenticatedAdminProvidersProviderIdRouteImport
      parentRoute: typeof AuthenticatedAdminProvidersRoute
    }
    '/_authenticated/admin/packages/new': {
      id: '/_authenticated/admin/packages/new'
      path: '/new'
      fullPath: '/admin/packages/new'
      preLoaderRoute: typeof AuthenticatedAdminPackagesNewRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
    '/_authenticated/admin/packages/$packageId': {
      id: '/_authenticated/admin/packages/$packageId'
      path: '/$packageId'
      fullPath: '/admin/packages/$packageId'
      preLoaderRoute: typeof AuthenticatedAdminPackagesPackageIdRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
    '/_authenticated/admin/medicines/new': {
      id: '/_authenticated/admin/medicines/new'
      path: '/new'
      fullPath: '/admin/medicines/new'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesNewRouteImport
      parentRoute: typeof AuthenticatedAdminMedicinesRoute
    }
    '/_authenticated/admin/medicines/$medicineId': {
      id: '/_authenticated/admin/medicines/$medicineId'
      path: '/$medicineId'
      fullPath: '/admin/medicines/$medicineId'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesMedicineIdRouteImport
      parentRoute: typeof AuthenticatedAdminMedicinesRoute
    }
  }
}

interface AuthenticatedAdminMedicinesRouteChildren {
  AuthenticatedAdminMedicinesMedicineIdRoute: typeof AuthenticatedAdminMedicinesMedicineIdRoute
  AuthenticatedAdminMedicinesNewRoute: typeof AuthenticatedAdminMedicinesNewRoute
  AuthenticatedAdminMedicinesIndexRoute: typeof AuthenticatedAdminMedicinesIndexRoute
}

const AuthenticatedAdminMedicinesRouteChildren: AuthenticatedAdminMedicinesRouteChildren =
  {
    AuthenticatedAdminMedicinesMedicineIdRoute:
      AuthenticatedAdminMedicinesMedicineIdRoute,
    AuthenticatedAdminMedicinesNewRoute: AuthenticatedAdminMedicinesNewRoute,
    AuthenticatedAdminMedicinesIndexRoute:
      AuthenticatedAdminMedicinesIndexRoute,
  }

const AuthenticatedAdminMedicinesRouteWithChildren =
  AuthenticatedAdminMedicinesRoute._addFileChildren(
    AuthenticatedAdminMedicinesRouteChildren,
  )

interface AuthenticatedAdminPackagesRouteChildren {
  AuthenticatedAdminPackagesPackageIdRoute: typeof AuthenticatedAdminPackagesPackageIdRoute
  AuthenticatedAdminPackagesNewRoute: typeof AuthenticatedAdminPackagesNewRoute
  AuthenticatedAdminPackagesIndexRoute: typeof AuthenticatedAdminPackagesIndexRoute
}

const AuthenticatedAdminPackagesRouteChildren: AuthenticatedAdminPackagesRouteChildren =
  {
    AuthenticatedAdminPackagesPackageIdRoute:
      AuthenticatedAdminPackagesPackageIdRoute,
    AuthenticatedAdminPackagesNewRoute: AuthenticatedAdminPackagesNewRoute,
    AuthenticatedAdminPackagesIndexRoute: AuthenticatedAdminPackagesIndexRoute,
  }

const AuthenticatedAdminPackagesRouteWithChildren =
  AuthenticatedAdminPackagesRoute._addFileChildren(
    AuthenticatedAdminPackagesRouteChildren,
  )

interface AuthenticatedAdminProvidersRouteChildren {
  AuthenticatedAdminProvidersProviderIdRoute: typeof AuthenticatedAdminProvidersProviderIdRoute
  AuthenticatedAdminProvidersNewRoute: typeof AuthenticatedAdminProvidersNewRoute
  AuthenticatedAdminProvidersIndexRoute: typeof AuthenticatedAdminProvidersIndexRoute
}

const AuthenticatedAdminProvidersRouteChildren: AuthenticatedAdminProvidersRouteChildren =
  {
    AuthenticatedAdminProvidersProviderIdRoute:
      AuthenticatedAdminProvidersProviderIdRoute,
    AuthenticatedAdminProvidersNewRoute: AuthenticatedAdminProvidersNewRoute,
    AuthenticatedAdminProvidersIndexRoute:
      AuthenticatedAdminProvidersIndexRoute,
  }

const AuthenticatedAdminProvidersRouteWithChildren =
  AuthenticatedAdminProvidersRoute._addFileChildren(
    AuthenticatedAdminProvidersRouteChildren,
  )

interface AuthenticatedAdminQuestionsRouteChildren {
  AuthenticatedAdminQuestionsQuestionIdRoute: typeof AuthenticatedAdminQuestionsQuestionIdRoute
  AuthenticatedAdminQuestionsNewRoute: typeof AuthenticatedAdminQuestionsNewRoute
  AuthenticatedAdminQuestionsIndexRoute: typeof AuthenticatedAdminQuestionsIndexRoute
}

const AuthenticatedAdminQuestionsRouteChildren: AuthenticatedAdminQuestionsRouteChildren =
  {
    AuthenticatedAdminQuestionsQuestionIdRoute:
      AuthenticatedAdminQuestionsQuestionIdRoute,
    AuthenticatedAdminQuestionsNewRoute: AuthenticatedAdminQuestionsNewRoute,
    AuthenticatedAdminQuestionsIndexRoute:
      AuthenticatedAdminQuestionsIndexRoute,
  }

const AuthenticatedAdminQuestionsRouteWithChildren =
  AuthenticatedAdminQuestionsRoute._addFileChildren(
    AuthenticatedAdminQuestionsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIntakeFormRoute: typeof AuthenticatedAdminIntakeFormRoute
  AuthenticatedAdminMedicinesRoute: typeof AuthenticatedAdminMedicinesRouteWithChildren
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRouteWithChildren
  AuthenticatedAdminPatientsRoute: typeof AuthenticatedAdminPatientsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRouteWithChildren
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRouteWithChildren
  AuthenticatedAdminSlotsRoute: typeof AuthenticatedAdminSlotsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIntakeFormRoute: AuthenticatedAdminIntakeFormRoute,
  AuthenticatedAdminMedicinesRoute:
    AuthenticatedAdminMedicinesRouteWithChildren,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRouteWithChildren,
  AuthenticatedAdminPatientsRoute: AuthenticatedAdminPatientsRoute,
  AuthenticatedAdminProvidersRoute:
    AuthenticatedAdminProvidersRouteWithChildren,
  AuthenticatedAdminQuestionsRoute:
    AuthenticatedAdminQuestionsRouteWithChildren,
  AuthenticatedAdminSlotsRoute: AuthenticatedAdminSlotsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
