/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSlotsRouteImport } from './routes/_authenticated/admin.slots'
import { Route as AuthenticatedAdminQuestionnairesRouteImport } from './routes/_authenticated/admin.questionnaires'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminPatientsRouteImport } from './routes/_authenticated/admin.patients'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin.packages'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminMedicinesRouteImport } from './routes/_authenticated/admin.medicines'
import { Route as AuthenticatedAdminMedicationRulesRouteImport } from './routes/_authenticated/admin.medication-rules'
import { Route as AuthenticatedAdminIntakeSessionsRouteImport } from './routes/_authenticated/admin.intake-sessions'
import { Route as AuthenticatedAdminIntakeFormRouteImport } from './routes/_authenticated/admin.intake-form'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminQuestionnairesIndexRouteImport } from './routes/_authenticated/admin.questionnaires.index'
import { Route as AuthenticatedAdminProvidersIndexRouteImport } from './routes/_authenticated/admin.providers.index'
import { Route as AuthenticatedAdminPatientsIndexRouteImport } from './routes/_authenticated/admin.patients.index'
import { Route as AuthenticatedAdminPackagesIndexRouteImport } from './routes/_authenticated/admin.packages.index'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin.orders.index'
import { Route as AuthenticatedAdminMedicinesIndexRouteImport } from './routes/_authenticated/admin.medicines.index'
import { Route as AuthenticatedAdminMedicationRulesIndexRouteImport } from './routes/_authenticated/admin.medication-rules.index'
import { Route as AuthenticatedAdminIntakeSessionsIndexRouteImport } from './routes/_authenticated/admin.intake-sessions.index'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin.categories.index'
import { Route as AuthenticatedAdminQuestionnairesNewRouteImport } from './routes/_authenticated/admin.questionnaires.new'
import { Route as AuthenticatedAdminQuestionnairesQuestionnaireIdRouteImport } from './routes/_authenticated/admin.questionnaires.$questionnaireId'
import { Route as AuthenticatedAdminProvidersNewRouteImport } from './routes/_authenticated/admin.providers.new'
import { Route as AuthenticatedAdminProvidersProviderIdRouteImport } from './routes/_authenticated/admin.providers.$providerId'
import { Route as AuthenticatedAdminPatientsPatientIdRouteImport } from './routes/_authenticated/admin.patients.$patientId'
import { Route as AuthenticatedAdminPackagesNewRouteImport } from './routes/_authenticated/admin.packages.new'
import { Route as AuthenticatedAdminPackagesPackageIdRouteImport } from './routes/_authenticated/admin.packages.$packageId'
import { Route as AuthenticatedAdminOrdersOrderIdRouteImport } from './routes/_authenticated/admin.orders.$orderId'
import { Route as AuthenticatedAdminMedicinesNewRouteImport } from './routes/_authenticated/admin.medicines.new'
import { Route as AuthenticatedAdminMedicinesMedicineIdRouteImport } from './routes/_authenticated/admin.medicines.$medicineId'
import { Route as AuthenticatedAdminCategoriesNewRouteImport } from './routes/_authenticated/admin.categories.new'
import { Route as AuthenticatedAdminCategoriesCategoryIdRouteImport } from './routes/_authenticated/admin.categories.$categoryId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSlotsRoute = AuthenticatedAdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQuestionnairesRoute =
  AuthenticatedAdminQuestionnairesRouteImport.update({
    id: '/questionnaires',
    path: '/questionnaires',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPatientsRoute =
  AuthenticatedAdminPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMedicinesRoute =
  AuthenticatedAdminMedicinesRouteImport.update({
    id: '/medicines',
    path: '/medicines',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMedicationRulesRoute =
  AuthenticatedAdminMedicationRulesRouteImport.update({
    id: '/medication-rules',
    path: '/medication-rules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntakeSessionsRoute =
  AuthenticatedAdminIntakeSessionsRouteImport.update({
    id: '/intake-sessions',
    path: '/intake-sessions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntakeFormRoute =
  AuthenticatedAdminIntakeFormRouteImport.update({
    id: '/intake-form',
    path: '/intake-form',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionnairesIndexRoute =
  AuthenticatedAdminQuestionnairesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminQuestionnairesRoute,
  } as any)
const AuthenticatedAdminProvidersIndexRoute =
  AuthenticatedAdminProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProvidersRoute,
  } as any)
const AuthenticatedAdminPatientsIndexRoute =
  AuthenticatedAdminPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPatientsRoute,
  } as any)
const AuthenticatedAdminPackagesIndexRoute =
  AuthenticatedAdminPackagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAdminMedicinesIndexRoute =
  AuthenticatedAdminMedicinesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminMedicinesRoute,
  } as any)
const AuthenticatedAdminMedicationRulesIndexRoute =
  AuthenticatedAdminMedicationRulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminMedicationRulesRoute,
  } as any)
const AuthenticatedAdminIntakeSessionsIndexRoute =
  AuthenticatedAdminIntakeSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminIntakeSessionsRoute,
  } as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminQuestionnairesNewRoute =
  AuthenticatedAdminQuestionnairesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminQuestionnairesRoute,
  } as any)
const AuthenticatedAdminQuestionnairesQuestionnaireIdRoute =
  AuthenticatedAdminQuestionnairesQuestionnaireIdRouteImport.update({
    id: '/$questionnaireId',
    path: '/$questionnaireId',
    getParentRoute: () => AuthenticatedAdminQuestionnairesRoute,
  } as any)
const AuthenticatedAdminProvidersNewRoute =
  AuthenticatedAdminProvidersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProvidersRoute,
  } as any)
const AuthenticatedAdminProvidersProviderIdRoute =
  AuthenticatedAdminProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AuthenticatedAdminProvidersRoute,
  } as any)
const AuthenticatedAdminPatientsPatientIdRoute =
  AuthenticatedAdminPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedAdminPatientsRoute,
  } as any)
const AuthenticatedAdminPackagesNewRoute =
  AuthenticatedAdminPackagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)
const AuthenticatedAdminPackagesPackageIdRoute =
  AuthenticatedAdminPackagesPackageIdRouteImport.update({
    id: '/$packageId',
    path: '/$packageId',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)
const AuthenticatedAdminOrdersOrderIdRoute =
  AuthenticatedAdminOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAdminMedicinesNewRoute =
  AuthenticatedAdminMedicinesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminMedicinesRoute,
  } as any)
const AuthenticatedAdminMedicinesMedicineIdRoute =
  AuthenticatedAdminMedicinesMedicineIdRouteImport.update({
    id: '/$medicineId',
    path: '/$medicineId',
    getParentRoute: () => AuthenticatedAdminMedicinesRoute,
  } as any)
const AuthenticatedAdminCategoriesNewRoute =
  AuthenticatedAdminCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesCategoryIdRoute =
  AuthenticatedAdminCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/admin/intake-form': typeof AuthenticatedAdminIntakeFormRoute
  '/admin/intake-sessions': typeof AuthenticatedAdminIntakeSessionsRouteWithChildren
  '/admin/medication-rules': typeof AuthenticatedAdminMedicationRulesRouteWithChildren
  '/admin/medicines': typeof AuthenticatedAdminMedicinesRouteWithChildren
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/admin/patients': typeof AuthenticatedAdminPatientsRouteWithChildren
  '/admin/providers': typeof AuthenticatedAdminProvidersRouteWithChildren
  '/admin/questionnaires': typeof AuthenticatedAdminQuestionnairesRouteWithChildren
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/categories/$categoryId': typeof AuthenticatedAdminCategoriesCategoryIdRoute
  '/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/admin/medicines/$medicineId': typeof AuthenticatedAdminMedicinesMedicineIdRoute
  '/admin/medicines/new': typeof AuthenticatedAdminMedicinesNewRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/admin/packages/$packageId': typeof AuthenticatedAdminPackagesPackageIdRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/patients/$patientId': typeof AuthenticatedAdminPatientsPatientIdRoute
  '/admin/providers/$providerId': typeof AuthenticatedAdminProvidersProviderIdRoute
  '/admin/providers/new': typeof AuthenticatedAdminProvidersNewRoute
  '/admin/questionnaires/$questionnaireId': typeof AuthenticatedAdminQuestionnairesQuestionnaireIdRoute
  '/admin/questionnaires/new': typeof AuthenticatedAdminQuestionnairesNewRoute
  '/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/intake-sessions/': typeof AuthenticatedAdminIntakeSessionsIndexRoute
  '/admin/medication-rules/': typeof AuthenticatedAdminMedicationRulesIndexRoute
  '/admin/medicines/': typeof AuthenticatedAdminMedicinesIndexRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/packages/': typeof AuthenticatedAdminPackagesIndexRoute
  '/admin/patients/': typeof AuthenticatedAdminPatientsIndexRoute
  '/admin/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/admin/questionnaires/': typeof AuthenticatedAdminQuestionnairesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/intake-form': typeof AuthenticatedAdminIntakeFormRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/categories/$categoryId': typeof AuthenticatedAdminCategoriesCategoryIdRoute
  '/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/admin/medicines/$medicineId': typeof AuthenticatedAdminMedicinesMedicineIdRoute
  '/admin/medicines/new': typeof AuthenticatedAdminMedicinesNewRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/admin/packages/$packageId': typeof AuthenticatedAdminPackagesPackageIdRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/patients/$patientId': typeof AuthenticatedAdminPatientsPatientIdRoute
  '/admin/providers/$providerId': typeof AuthenticatedAdminProvidersProviderIdRoute
  '/admin/providers/new': typeof AuthenticatedAdminProvidersNewRoute
  '/admin/questionnaires/$questionnaireId': typeof AuthenticatedAdminQuestionnairesQuestionnaireIdRoute
  '/admin/questionnaires/new': typeof AuthenticatedAdminQuestionnairesNewRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/intake-sessions': typeof AuthenticatedAdminIntakeSessionsIndexRoute
  '/admin/medication-rules': typeof AuthenticatedAdminMedicationRulesIndexRoute
  '/admin/medicines': typeof AuthenticatedAdminMedicinesIndexRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesIndexRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsIndexRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersIndexRoute
  '/admin/questionnaires': typeof AuthenticatedAdminQuestionnairesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/_authenticated/admin/intake-form': typeof AuthenticatedAdminIntakeFormRoute
  '/_authenticated/admin/intake-sessions': typeof AuthenticatedAdminIntakeSessionsRouteWithChildren
  '/_authenticated/admin/medication-rules': typeof AuthenticatedAdminMedicationRulesRouteWithChildren
  '/_authenticated/admin/medicines': typeof AuthenticatedAdminMedicinesRouteWithChildren
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/_authenticated/admin/patients': typeof AuthenticatedAdminPatientsRouteWithChildren
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRouteWithChildren
  '/_authenticated/admin/questionnaires': typeof AuthenticatedAdminQuestionnairesRouteWithChildren
  '/_authenticated/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/categories/$categoryId': typeof AuthenticatedAdminCategoriesCategoryIdRoute
  '/_authenticated/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/_authenticated/admin/medicines/$medicineId': typeof AuthenticatedAdminMedicinesMedicineIdRoute
  '/_authenticated/admin/medicines/new': typeof AuthenticatedAdminMedicinesNewRoute
  '/_authenticated/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/_authenticated/admin/packages/$packageId': typeof AuthenticatedAdminPackagesPackageIdRoute
  '/_authenticated/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/_authenticated/admin/patients/$patientId': typeof AuthenticatedAdminPatientsPatientIdRoute
  '/_authenticated/admin/providers/$providerId': typeof AuthenticatedAdminProvidersProviderIdRoute
  '/_authenticated/admin/providers/new': typeof AuthenticatedAdminProvidersNewRoute
  '/_authenticated/admin/questionnaires/$questionnaireId': typeof AuthenticatedAdminQuestionnairesQuestionnaireIdRoute
  '/_authenticated/admin/questionnaires/new': typeof AuthenticatedAdminQuestionnairesNewRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/intake-sessions/': typeof AuthenticatedAdminIntakeSessionsIndexRoute
  '/_authenticated/admin/medication-rules/': typeof AuthenticatedAdminMedicationRulesIndexRoute
  '/_authenticated/admin/medicines/': typeof AuthenticatedAdminMedicinesIndexRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/packages/': typeof AuthenticatedAdminPackagesIndexRoute
  '/_authenticated/admin/patients/': typeof AuthenticatedAdminPatientsIndexRoute
  '/_authenticated/admin/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/_authenticated/admin/questionnaires/': typeof AuthenticatedAdminQuestionnairesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/admin/categories'
    | '/admin/intake-form'
    | '/admin/intake-sessions'
    | '/admin/medication-rules'
    | '/admin/medicines'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/patients'
    | '/admin/providers'
    | '/admin/questionnaires'
    | '/admin/slots'
    | '/admin/'
    | '/admin/categories/$categoryId'
    | '/admin/categories/new'
    | '/admin/medicines/$medicineId'
    | '/admin/medicines/new'
    | '/admin/orders/$orderId'
    | '/admin/packages/$packageId'
    | '/admin/packages/new'
    | '/admin/patients/$patientId'
    | '/admin/providers/$providerId'
    | '/admin/providers/new'
    | '/admin/questionnaires/$questionnaireId'
    | '/admin/questionnaires/new'
    | '/admin/categories/'
    | '/admin/intake-sessions/'
    | '/admin/medication-rules/'
    | '/admin/medicines/'
    | '/admin/orders/'
    | '/admin/packages/'
    | '/admin/patients/'
    | '/admin/providers/'
    | '/admin/questionnaires/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard'
    | '/admin/intake-form'
    | '/admin/slots'
    | '/admin'
    | '/admin/categories/$categoryId'
    | '/admin/categories/new'
    | '/admin/medicines/$medicineId'
    | '/admin/medicines/new'
    | '/admin/orders/$orderId'
    | '/admin/packages/$packageId'
    | '/admin/packages/new'
    | '/admin/patients/$patientId'
    | '/admin/providers/$providerId'
    | '/admin/providers/new'
    | '/admin/questionnaires/$questionnaireId'
    | '/admin/questionnaires/new'
    | '/admin/categories'
    | '/admin/intake-sessions'
    | '/admin/medication-rules'
    | '/admin/medicines'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/patients'
    | '/admin/providers'
    | '/admin/questionnaires'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/intake-form'
    | '/_authenticated/admin/intake-sessions'
    | '/_authenticated/admin/medication-rules'
    | '/_authenticated/admin/medicines'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/patients'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/questionnaires'
    | '/_authenticated/admin/slots'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/categories/$categoryId'
    | '/_authenticated/admin/categories/new'
    | '/_authenticated/admin/medicines/$medicineId'
    | '/_authenticated/admin/medicines/new'
    | '/_authenticated/admin/orders/$orderId'
    | '/_authenticated/admin/packages/$packageId'
    | '/_authenticated/admin/packages/new'
    | '/_authenticated/admin/patients/$patientId'
    | '/_authenticated/admin/providers/$providerId'
    | '/_authenticated/admin/providers/new'
    | '/_authenticated/admin/questionnaires/$questionnaireId'
    | '/_authenticated/admin/questionnaires/new'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/intake-sessions/'
    | '/_authenticated/admin/medication-rules/'
    | '/_authenticated/admin/medicines/'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/packages/'
    | '/_authenticated/admin/patients/'
    | '/_authenticated/admin/providers/'
    | '/_authenticated/admin/questionnaires/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/slots': {
      id: '/_authenticated/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AuthenticatedAdminSlotsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questionnaires': {
      id: '/_authenticated/admin/questionnaires'
      path: '/questionnaires'
      fullPath: '/admin/questionnaires'
      preLoaderRoute: typeof AuthenticatedAdminQuestionnairesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/patients': {
      id: '/_authenticated/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AuthenticatedAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/medicines': {
      id: '/_authenticated/admin/medicines'
      path: '/medicines'
      fullPath: '/admin/medicines'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/medication-rules': {
      id: '/_authenticated/admin/medication-rules'
      path: '/medication-rules'
      fullPath: '/admin/medication-rules'
      preLoaderRoute: typeof AuthenticatedAdminMedicationRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/intake-sessions': {
      id: '/_authenticated/admin/intake-sessions'
      path: '/intake-sessions'
      fullPath: '/admin/intake-sessions'
      preLoaderRoute: typeof AuthenticatedAdminIntakeSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/intake-form': {
      id: '/_authenticated/admin/intake-form'
      path: '/intake-form'
      fullPath: '/admin/intake-form'
      preLoaderRoute: typeof AuthenticatedAdminIntakeFormRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questionnaires/': {
      id: '/_authenticated/admin/questionnaires/'
      path: '/'
      fullPath: '/admin/questionnaires/'
      preLoaderRoute: typeof AuthenticatedAdminQuestionnairesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminQuestionnairesRoute
    }
    '/_authenticated/admin/providers/': {
      id: '/_authenticated/admin/providers/'
      path: '/'
      fullPath: '/admin/providers/'
      preLoaderRoute: typeof AuthenticatedAdminProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProvidersRoute
    }
    '/_authenticated/admin/patients/': {
      id: '/_authenticated/admin/patients/'
      path: '/'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AuthenticatedAdminPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPatientsRoute
    }
    '/_authenticated/admin/packages/': {
      id: '/_authenticated/admin/packages/'
      path: '/'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AuthenticatedAdminPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/admin/medicines/': {
      id: '/_authenticated/admin/medicines/'
      path: '/'
      fullPath: '/admin/medicines/'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminMedicinesRoute
    }
    '/_authenticated/admin/medication-rules/': {
      id: '/_authenticated/admin/medication-rules/'
      path: '/'
      fullPath: '/admin/medication-rules/'
      preLoaderRoute: typeof AuthenticatedAdminMedicationRulesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminMedicationRulesRoute
    }
    '/_authenticated/admin/intake-sessions/': {
      id: '/_authenticated/admin/intake-sessions/'
      path: '/'
      fullPath: '/admin/intake-sessions/'
      preLoaderRoute: typeof AuthenticatedAdminIntakeSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminIntakeSessionsRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/questionnaires/new': {
      id: '/_authenticated/admin/questionnaires/new'
      path: '/new'
      fullPath: '/admin/questionnaires/new'
      preLoaderRoute: typeof AuthenticatedAdminQuestionnairesNewRouteImport
      parentRoute: typeof AuthenticatedAdminQuestionnairesRoute
    }
    '/_authenticated/admin/questionnaires/$questionnaireId': {
      id: '/_authenticated/admin/questionnaires/$questionnaireId'
      path: '/$questionnaireId'
      fullPath: '/admin/questionnaires/$questionnaireId'
      preLoaderRoute: typeof AuthenticatedAdminQuestionnairesQuestionnaireIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuestionnairesRoute
    }
    '/_authenticated/admin/providers/new': {
      id: '/_authenticated/admin/providers/new'
      path: '/new'
      fullPath: '/admin/providers/new'
      preLoaderRoute: typeof AuthenticatedAdminProvidersNewRouteImport
      parentRoute: typeof AuthenticatedAdminProvidersRoute
    }
    '/_authenticated/admin/providers/$providerId': {
      id: '/_authenticated/admin/providers/$providerId'
      path: '/$providerId'
      fullPath: '/admin/providers/$providerId'
      preLoaderRoute: typeof AuthenticatedAdminProvidersProviderIdRouteImport
      parentRoute: typeof AuthenticatedAdminProvidersRoute
    }
    '/_authenticated/admin/patients/$patientId': {
      id: '/_authenticated/admin/patients/$patientId'
      path: '/$patientId'
      fullPath: '/admin/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedAdminPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedAdminPatientsRoute
    }
    '/_authenticated/admin/packages/new': {
      id: '/_authenticated/admin/packages/new'
      path: '/new'
      fullPath: '/admin/packages/new'
      preLoaderRoute: typeof AuthenticatedAdminPackagesNewRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
    '/_authenticated/admin/packages/$packageId': {
      id: '/_authenticated/admin/packages/$packageId'
      path: '/$packageId'
      fullPath: '/admin/packages/$packageId'
      preLoaderRoute: typeof AuthenticatedAdminPackagesPackageIdRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
    '/_authenticated/admin/orders/$orderId': {
      id: '/_authenticated/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/admin/medicines/new': {
      id: '/_authenticated/admin/medicines/new'
      path: '/new'
      fullPath: '/admin/medicines/new'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesNewRouteImport
      parentRoute: typeof AuthenticatedAdminMedicinesRoute
    }
    '/_authenticated/admin/medicines/$medicineId': {
      id: '/_authenticated/admin/medicines/$medicineId'
      path: '/$medicineId'
      fullPath: '/admin/medicines/$medicineId'
      preLoaderRoute: typeof AuthenticatedAdminMedicinesMedicineIdRouteImport
      parentRoute: typeof AuthenticatedAdminMedicinesRoute
    }
    '/_authenticated/admin/categories/new': {
      id: '/_authenticated/admin/categories/new'
      path: '/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/$categoryId': {
      id: '/_authenticated/admin/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
  }
}

interface AuthenticatedAdminCategoriesRouteChildren {
  AuthenticatedAdminCategoriesCategoryIdRoute: typeof AuthenticatedAdminCategoriesCategoryIdRoute
  AuthenticatedAdminCategoriesNewRoute: typeof AuthenticatedAdminCategoriesNewRoute
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
}

const AuthenticatedAdminCategoriesRouteChildren: AuthenticatedAdminCategoriesRouteChildren =
  {
    AuthenticatedAdminCategoriesCategoryIdRoute:
      AuthenticatedAdminCategoriesCategoryIdRoute,
    AuthenticatedAdminCategoriesNewRoute: AuthenticatedAdminCategoriesNewRoute,
    AuthenticatedAdminCategoriesIndexRoute:
      AuthenticatedAdminCategoriesIndexRoute,
  }

const AuthenticatedAdminCategoriesRouteWithChildren =
  AuthenticatedAdminCategoriesRoute._addFileChildren(
    AuthenticatedAdminCategoriesRouteChildren,
  )

interface AuthenticatedAdminIntakeSessionsRouteChildren {
  AuthenticatedAdminIntakeSessionsIndexRoute: typeof AuthenticatedAdminIntakeSessionsIndexRoute
}

const AuthenticatedAdminIntakeSessionsRouteChildren: AuthenticatedAdminIntakeSessionsRouteChildren =
  {
    AuthenticatedAdminIntakeSessionsIndexRoute:
      AuthenticatedAdminIntakeSessionsIndexRoute,
  }

const AuthenticatedAdminIntakeSessionsRouteWithChildren =
  AuthenticatedAdminIntakeSessionsRoute._addFileChildren(
    AuthenticatedAdminIntakeSessionsRouteChildren,
  )

interface AuthenticatedAdminMedicationRulesRouteChildren {
  AuthenticatedAdminMedicationRulesIndexRoute: typeof AuthenticatedAdminMedicationRulesIndexRoute
}

const AuthenticatedAdminMedicationRulesRouteChildren: AuthenticatedAdminMedicationRulesRouteChildren =
  {
    AuthenticatedAdminMedicationRulesIndexRoute:
      AuthenticatedAdminMedicationRulesIndexRoute,
  }

const AuthenticatedAdminMedicationRulesRouteWithChildren =
  AuthenticatedAdminMedicationRulesRoute._addFileChildren(
    AuthenticatedAdminMedicationRulesRouteChildren,
  )

interface AuthenticatedAdminMedicinesRouteChildren {
  AuthenticatedAdminMedicinesMedicineIdRoute: typeof AuthenticatedAdminMedicinesMedicineIdRoute
  AuthenticatedAdminMedicinesNewRoute: typeof AuthenticatedAdminMedicinesNewRoute
  AuthenticatedAdminMedicinesIndexRoute: typeof AuthenticatedAdminMedicinesIndexRoute
}

const AuthenticatedAdminMedicinesRouteChildren: AuthenticatedAdminMedicinesRouteChildren =
  {
    AuthenticatedAdminMedicinesMedicineIdRoute:
      AuthenticatedAdminMedicinesMedicineIdRoute,
    AuthenticatedAdminMedicinesNewRoute: AuthenticatedAdminMedicinesNewRoute,
    AuthenticatedAdminMedicinesIndexRoute:
      AuthenticatedAdminMedicinesIndexRoute,
  }

const AuthenticatedAdminMedicinesRouteWithChildren =
  AuthenticatedAdminMedicinesRoute._addFileChildren(
    AuthenticatedAdminMedicinesRouteChildren,
  )

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersOrderIdRoute: typeof AuthenticatedAdminOrdersOrderIdRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersOrderIdRoute: AuthenticatedAdminOrdersOrderIdRoute,
    AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminPackagesRouteChildren {
  AuthenticatedAdminPackagesPackageIdRoute: typeof AuthenticatedAdminPackagesPackageIdRoute
  AuthenticatedAdminPackagesNewRoute: typeof AuthenticatedAdminPackagesNewRoute
  AuthenticatedAdminPackagesIndexRoute: typeof AuthenticatedAdminPackagesIndexRoute
}

const AuthenticatedAdminPackagesRouteChildren: AuthenticatedAdminPackagesRouteChildren =
  {
    AuthenticatedAdminPackagesPackageIdRoute:
      AuthenticatedAdminPackagesPackageIdRoute,
    AuthenticatedAdminPackagesNewRoute: AuthenticatedAdminPackagesNewRoute,
    AuthenticatedAdminPackagesIndexRoute: AuthenticatedAdminPackagesIndexRoute,
  }

const AuthenticatedAdminPackagesRouteWithChildren =
  AuthenticatedAdminPackagesRoute._addFileChildren(
    AuthenticatedAdminPackagesRouteChildren,
  )

interface AuthenticatedAdminPatientsRouteChildren {
  AuthenticatedAdminPatientsPatientIdRoute: typeof AuthenticatedAdminPatientsPatientIdRoute
  AuthenticatedAdminPatientsIndexRoute: typeof AuthenticatedAdminPatientsIndexRoute
}

const AuthenticatedAdminPatientsRouteChildren: AuthenticatedAdminPatientsRouteChildren =
  {
    AuthenticatedAdminPatientsPatientIdRoute:
      AuthenticatedAdminPatientsPatientIdRoute,
    AuthenticatedAdminPatientsIndexRoute: AuthenticatedAdminPatientsIndexRoute,
  }

const AuthenticatedAdminPatientsRouteWithChildren =
  AuthenticatedAdminPatientsRoute._addFileChildren(
    AuthenticatedAdminPatientsRouteChildren,
  )

interface AuthenticatedAdminProvidersRouteChildren {
  AuthenticatedAdminProvidersProviderIdRoute: typeof AuthenticatedAdminProvidersProviderIdRoute
  AuthenticatedAdminProvidersNewRoute: typeof AuthenticatedAdminProvidersNewRoute
  AuthenticatedAdminProvidersIndexRoute: typeof AuthenticatedAdminProvidersIndexRoute
}

const AuthenticatedAdminProvidersRouteChildren: AuthenticatedAdminProvidersRouteChildren =
  {
    AuthenticatedAdminProvidersProviderIdRoute:
      AuthenticatedAdminProvidersProviderIdRoute,
    AuthenticatedAdminProvidersNewRoute: AuthenticatedAdminProvidersNewRoute,
    AuthenticatedAdminProvidersIndexRoute:
      AuthenticatedAdminProvidersIndexRoute,
  }

const AuthenticatedAdminProvidersRouteWithChildren =
  AuthenticatedAdminProvidersRoute._addFileChildren(
    AuthenticatedAdminProvidersRouteChildren,
  )

interface AuthenticatedAdminQuestionnairesRouteChildren {
  AuthenticatedAdminQuestionnairesQuestionnaireIdRoute: typeof AuthenticatedAdminQuestionnairesQuestionnaireIdRoute
  AuthenticatedAdminQuestionnairesNewRoute: typeof AuthenticatedAdminQuestionnairesNewRoute
  AuthenticatedAdminQuestionnairesIndexRoute: typeof AuthenticatedAdminQuestionnairesIndexRoute
}

const AuthenticatedAdminQuestionnairesRouteChildren: AuthenticatedAdminQuestionnairesRouteChildren =
  {
    AuthenticatedAdminQuestionnairesQuestionnaireIdRoute:
      AuthenticatedAdminQuestionnairesQuestionnaireIdRoute,
    AuthenticatedAdminQuestionnairesNewRoute:
      AuthenticatedAdminQuestionnairesNewRoute,
    AuthenticatedAdminQuestionnairesIndexRoute:
      AuthenticatedAdminQuestionnairesIndexRoute,
  }

const AuthenticatedAdminQuestionnairesRouteWithChildren =
  AuthenticatedAdminQuestionnairesRoute._addFileChildren(
    AuthenticatedAdminQuestionnairesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRouteWithChildren
  AuthenticatedAdminIntakeFormRoute: typeof AuthenticatedAdminIntakeFormRoute
  AuthenticatedAdminIntakeSessionsRoute: typeof AuthenticatedAdminIntakeSessionsRouteWithChildren
  AuthenticatedAdminMedicationRulesRoute: typeof AuthenticatedAdminMedicationRulesRouteWithChildren
  AuthenticatedAdminMedicinesRoute: typeof AuthenticatedAdminMedicinesRouteWithChildren
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRouteWithChildren
  AuthenticatedAdminPatientsRoute: typeof AuthenticatedAdminPatientsRouteWithChildren
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRouteWithChildren
  AuthenticatedAdminQuestionnairesRoute: typeof AuthenticatedAdminQuestionnairesRouteWithChildren
  AuthenticatedAdminSlotsRoute: typeof AuthenticatedAdminSlotsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute:
    AuthenticatedAdminCategoriesRouteWithChildren,
  AuthenticatedAdminIntakeFormRoute: AuthenticatedAdminIntakeFormRoute,
  AuthenticatedAdminIntakeSessionsRoute:
    AuthenticatedAdminIntakeSessionsRouteWithChildren,
  AuthenticatedAdminMedicationRulesRoute:
    AuthenticatedAdminMedicationRulesRouteWithChildren,
  AuthenticatedAdminMedicinesRoute:
    AuthenticatedAdminMedicinesRouteWithChildren,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRouteWithChildren,
  AuthenticatedAdminPatientsRoute: AuthenticatedAdminPatientsRouteWithChildren,
  AuthenticatedAdminProvidersRoute:
    AuthenticatedAdminProvidersRouteWithChildren,
  AuthenticatedAdminQuestionnairesRoute:
    AuthenticatedAdminQuestionnairesRouteWithChildren,
  AuthenticatedAdminSlotsRoute: AuthenticatedAdminSlotsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
